
spring:
    datasource:
        name: test
        url: jdbc:mysql://118.31.46.55:3306/demo
        username: xxxxxx
        password: xxxxxx
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    aop:
      auto: true
mybatis:
  configuration-properties:
  configuration:
    map-underscore-to-camel-case: true